import type { Session, User as SupabaseUser } from '@supabase/supabase-js';
import { Collection, Post, Review, Spot } from '../types';

export const MOCK_MODE = process.env.EXPO_PUBLIC_MOCK_MODE === 'true';

const mockUser: SupabaseUser = {
  id: 'mock-user-1',
  app_metadata: {},
  user_metadata: {},
  aud: 'authenticated',
  created_at: new Date().toISOString(),
  email: 'preview@kuppio.app',
} as SupabaseUser;

export const mockSession: Session = {
  access_token: 'mock-access-token',
  refresh_token: 'mock-refresh-token',
  expires_in: 3600,
  token_type: 'bearer',
  user: mockUser,
} as Session;

export const mockSpots: Spot[] = [
  {
    id: 'spot-1',
    name: 'Fog City Matcha',
    category: 'matcha',
    tags: ['cozy', 'wifi', 'window seats'],
    isHomeBased: false,
    lat: 37.7699,
    lng: -122.4469,
    address: '1421 Irving St, San Francisco, CA',
    priceRange: '$$',
    description: 'Ceremonial-grade matcha bar tucked behind a laundromat. Ask for the strawberry matcha.',
    photos: ['https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800'],
    hours: [{ day: 'Sat', open: '8:00', close: '18:00' }],
    menu: [{ id: 'm1', name: 'Strawberry Matcha', price: 6.5, isPopular: true }],
    acceptingOrders: true,
    teaScore: 92,
    worthTheHypeVotes: 41,
    hiddenGemVotes: 18,
    ownerUserId: null,
    promotedUntil: null,
    published: true,
  },
  {
    id: 'spot-2',
    name: "Marisol's Kitchen",
    category: 'home_based',
    tags: ['home-based', 'preorder', 'tamales'],
    isHomeBased: true,
    lat: 37.8044,
    lng: -122.2711,
    serviceArea: 'Oakland, CA',
    priceRange: '$',
    description: 'Weekend tamales made in a licensed home kitchen. Sells out by noon.',
    photos: ['https://images.unsplash.com/photo-1584208632869-05fa2b2a5934?w=800'],
    hours: [{ day: 'Sun', open: '9:00', close: '13:00' }],
    menu: [{ id: 'm2', name: 'Dozen Tamales', price: 24, isPopular: true }],
    acceptingOrders: true,
    teaScore: 88,
    worthTheHypeVotes: 29,
    hiddenGemVotes: 33,
    ownerUserId: null,
    promotedUntil: null,
    published: true,
  },
  {
    id: 'spot-3',
    name: 'Sunset Push Cart',
    category: 'food_truck',
    tags: ['late night', 'cash only'],
    isHomeBased: false,
    lat: 37.7583,
    lng: -122.4869,
    address: 'Corner of Judah & 46th Ave, San Francisco, CA',
    priceRange: '$',
    description: 'Elote cart that only shows up after 9pm. Word of mouth only.',
    photos: ['https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800'],
    hours: [{ day: 'Fri', open: '21:00', close: '1:00' }],
    menu: [{ id: 'm3', name: 'Elote', price: 5, isPopular: true }],
    acceptingOrders: true,
    teaScore: 95,
    worthTheHypeVotes: 52,
    hiddenGemVotes: 61,
    ownerUserId: null,
    promotedUntil: null,
    published: true,
  },
];

export const mockPosts: Post[] = [
  {
    id: 'story-1',
    spotId: 'spot-1',
    userId: 'mock-user-2',
    authorType: 'customer',
    authorName: 'jamie.eats',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    mediaUrl: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800',
    isVideo: false,
    caption: 'Saturday matcha run ☕',
    exploreTags: [],
    likeCount: 0,
    commentCount: 0,
    shareCount: 0,
    isStory: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'story-2',
    spotId: 'spot-3',
    userId: 'mock-user-3',
    authorType: 'customer',
    authorName: 'sf.eats',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    mediaUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    isVideo: false,
    caption: 'late night elote 🌽',
    exploreTags: [],
    likeCount: 0,
    commentCount: 0,
    shareCount: 0,
    isStory: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'post-1',
    spotId: 'spot-1',
    userId: 'mock-user-2',
    authorType: 'customer',
    authorName: 'jamie.eats',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    mediaUrl: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800',
    isVideo: false,
    caption: 'found the best matcha in the city and nobody knows about it yet 🍵 #hiddengem',
    exploreTags: ['hiddengem', 'matcha'],
    likeCount: 214,
    commentCount: 12,
    shareCount: 4,
    isStory: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'post-2',
    spotId: 'spot-3',
    userId: 'mock-user-3',
    authorType: 'customer',
    authorName: 'foggy.foodie',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    mediaUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800',
    isVideo: false,
    caption: 'this elote cart only exists after 9pm and it changed my life',
    exploreTags: ['latenight', 'streetfood'],
    likeCount: 389,
    commentCount: 27,
    shareCount: 15,
    isStory: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    spotId: 'spot-1',
    userId: 'mock-user-2',
    userName: 'jamie.eats',
    userAvatar: 'https://i.pravatar.cc/150?img=5',
    ratingOverall: 5,
    ratingTaste: 5,
    ratingValue: 4,
    ratingVibe: 5,
    vibeTag: 'hidden_gem',
    text: 'Quiet, cozy, and the matcha is unreal. My new Saturday spot.',
    likeCount: 32,
    createdAt: new Date().toISOString(),
  },
];

export const mockCollections: Collection[] = [
  { id: 'col-1', name: 'Saturday Spots', description: 'Weekend go-tos', spotIds: ['spot-1'] },
];
